### ISSUE TITLE
Crash when analysing Glow Service.sln

### ISSUE THREAD

**Issue by yaakov-h** [WiseTechGlobal/BulkAnalysisRunner#4]
Stack trace:

```
Unhandled Exception: System.ArgumentException: Argument contains duplicate analyzer instances.
Parameter name: analyzers
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.VerifyAnalyzersArgumentForStaticApis(ImmutableArray`1 analyzers, Boolean allowDefaultOrEmpty)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.VerifyArguments(Compilation compilation, ImmutableArray`1 analyzers, CompilationWithAnalyzersOptions analysisOptions)
   at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers..ctor(Compilation compilation, ImmutableArray`1 analyzers, CompilationWithAnalyzersOptions analysisOptions, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerExtensions.WithAnalyzers(Compilation compilation, ImmutableArray`1 analyzers, CompilationWithAnalyzersOptions analysisOptions)
   at WTG.BulkAnalysis.Core.SolutionProcessor.<GetProjectAnalyzerDiagnosticsAsync>d__4.MoveNext() in C:\git\GitHub\WiseTechGlobal\BulkAnalysisRunner\src\WTG.BulkAnalysis.Core\Internal\SolutionProcessor.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Core.SolutionProcessor.<GetAnalyzerDiagnosticsAsync>d__3.MoveNext() in C:\git\GitHub\WiseTechGlobal\BulkAnalysisRunner\src\WTG.BulkAnalysis.Core\Internal\SolutionProcessor.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Core.SolutionProcessor.<ProcessSolutionAsync>d__1.MoveNext() in C:\git\GitHub\WiseTechGlobal\BulkAnalysisRunner\src\WTG.BulkAnalysis.Core\Internal\SolutionProcessor.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Core.Processor.<ProcessAsync>d__0.MoveNext() in C:\git\GitHub\WiseTechGlobal\BulkAnalysisRunner\src\WTG.BulkAnalysis.Core\Processor.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Runner.Program.<MainAsync>d__1.MoveNext() in C:\git\GitHub\WiseTechGlobal\BulkAnalysisRunner\src\WTG.BulkAnalysis.Runner\Program.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Runner.Program.<Main>d__0.MoveNext() in C:\git\GitHub\WiseTechGlobal\BulkAnalysisRunner\src\WTG.BulkAnalysis.Runner\Program.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WTG.BulkAnalysis.Runner.Program.<Main>(String[] args)
```

I think what has happened is this solution has a mixture of old-csproj and new-csproj projects.

The old-csproj projects import from the NuGet cache (`%userprofile%\.nuget\packages\WTG.Analyzers\version\...`) whereas the new-csproj projects import from Paket's folder in the repo (`packages\Build\WTG.Analyzers\...`).

When this is remapped with `-loadDir` we land up with two paths to the exact same WTG.Analyzers DLL, load the exact same Analyzer twice, and provide two of the exact same analyser to Roslyn, which then fails with this exception.

The failure can first be observed here when debugging, we land up with two identical analyzer objects: https://github.com/WiseTechGlobal/BulkAnalysisRunner/blob/46448f6c8cc3aaf0a788b9acb4aa700f95e3e654/src/WTG.BulkAnalysis.Core/Internal/AnalyzerCache.cs#L69-L72

As a workaround I have wrapped the LINQ query with `(...).Distinct()` but I'm uncertain as to whether this is the "correct" fix or not.

**Comment by brian-reichle** [comment]
The project references the same analyzer dll via two separate paths? that kinda feels wrong to me. We can probably make BulkAnalysisRunner more robust to the situation, but if we do then we should still issue a warning when it happens.

**Comment by yaakov-h** [comment]
Each **project** seems to have only one path to the DLL, but the **solution** holds two, I assume aggregated from the child projects.

I haven't dug further to see exactly how we extricate those paths but we seem to deal with analysers at a solution level, not at a project level.

**Comment by brian-reichle** [comment]
it seems we extract [all the analyzers for all the projects](https://github.com/WiseTechGlobal/BulkAnalysisRunner/blob/46448f6c8cc3aaf0a788b9acb4aa700f95e3e654/src/WTG.BulkAnalysis.Core/Internal/AnalyzerCache.cs#L108) in the solution, then [apply all those analyzers to all the projects](https://github.com/WiseTechGlobal/BulkAnalysisRunner/blob/46448f6c8cc3aaf0a788b9acb4aa700f95e3e654/src/WTG.BulkAnalysis.Core/Internal/SolutionProcessor.cs#L129). Should probably calculate the set of analyzers on a per-project basis instead.

**Comment by brian-reichle** [comment]
https://github.com/WiseTechGlobal/BulkAnalysisRunner/compare/per-project

**Comment by yaakov-h** [comment]
👍 

That branch seems to do the trick.
